package teabooker.model;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EventGroup generated by hbm2java
 */
public class EventGroupInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3058031854660492872L;
	private Integer id;
	private int eventId;
	private int groupId;
	private Date createdDate;
	private GroupInfo eventGroup;


	public GroupInfo getEventGroup() {
		return eventGroup;
	}

	public void setEventGroup(GroupInfo eventGroup) {
		this.eventGroup = eventGroup;
	}

	public EventGroupInfo() {
	}

	public EventGroupInfo(int eventId, int groupId, Date createdDate) {
		this.eventId = eventId;
		this.groupId = groupId;
		this.createdDate = createdDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
