package teabooker.model;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Eventinfo generated by hbm2java
 */
public class EventInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5467692277639804907L;
	private Integer eventId;
	private int eventStatus;
	private int ownerId;
	private Date eventStartTime;
	private Date eventEndTime;
	private int phase;
	private String eventName;

	public EventInfo() {
	}

	public EventInfo(int eventStatus, int ownerId, Date eventStartTime,
			Date eventEndTime, int phase, String eventName) {
		this.eventStatus = eventStatus;
		this.ownerId = ownerId;
		this.eventStartTime = eventStartTime;
		this.eventEndTime = eventEndTime;
		this.phase = phase;
		this.eventName = eventName;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public int getEventStatus() {
		return this.eventStatus;
	}

	public void setEventStatus(int eventStatus) {
		this.eventStatus = eventStatus;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public Date getEventStartTime() {
		return this.eventStartTime;
	}

	public void setEventStartTime(Date eventStartTime) {
		this.eventStartTime = eventStartTime;
	}

	public Date getEventEndTime() {
		return this.eventEndTime;
	}

	public void setEventEndTime(Date eventEndTime) {
		this.eventEndTime = eventEndTime;
	}

	public int getPhase() {
		return this.phase;
	}

	public void setPhase(int phase) {
		this.phase = phase;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

}
