package teabooker.model;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventShop generated by hbm2java
 */
public class EventShopInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6806960986263328155L;
	private Integer id;
	private int eventId;
	private int shopId;
	private int shopAddressId;
	private ShopInfo shopInfo;
	private ShopAddressInfo addressInfo;

	public ShopInfo getShopInfo() {
		return shopInfo;
	}

	public void setShopInfo(ShopInfo shopInfo) {
		this.shopInfo = shopInfo;
	}

	public ShopAddressInfo getAddressInfo() {
		return addressInfo;
	}

	public void setAddressInfo(ShopAddressInfo addressInfo) {
		this.addressInfo = addressInfo;
	}

	public EventShopInfo() {
	}

	public EventShopInfo(int eventId, int shopId, int shopAddressId) {
		this.eventId = eventId;
		this.shopId = shopId;
		this.shopAddressId = shopAddressId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public int getShopAddressId() {
		return this.shopAddressId;
	}

	public void setShopAddressId(int shopAddressId) {
		this.shopAddressId = shopAddressId;
	}

}
