package teabooker.model;

import java.util.Set;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Food generated by hbm2java
 */
public class FoodInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4560681700733584360L;
	private Integer foodId;
	private String foodName;
	private String foodPrice;
	private int foodStatus;
	private int shopId;
	private String thumbnail;
	
	private transient Set<OrderInfo> orderInfoSet;

	public Set<OrderInfo> getOrderInfoSet() {
		return orderInfoSet;
	}

	public void setOrderInfoSet(Set<OrderInfo> orderInfoSet) {
		this.orderInfoSet = orderInfoSet;
	}

	public FoodInfo() {
	}

	public FoodInfo(String foodName, String foodPrice, int foodStatus,
			int shopId) {
		this.foodName = foodName;
		this.foodPrice = foodPrice;
		this.foodStatus = foodStatus;
		this.shopId = shopId;
	}

	public FoodInfo(String foodName, String foodPrice, int foodStatus,
			int shopId, String thumbnail) {
		this.foodName = foodName;
		this.foodPrice = foodPrice;
		this.foodStatus = foodStatus;
		this.shopId = shopId;
		this.thumbnail = thumbnail;
	}

	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public String getFoodPrice() {
		return this.foodPrice.trim();
	}

	public void setFoodPrice(String foodPrice) {
		this.foodPrice = foodPrice.trim();
	}

	public int getFoodStatus() {
		return this.foodStatus;
	}

	public void setFoodStatus(int foodStatus) {
		this.foodStatus = foodStatus;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

}
