package teabooker.model;

// Generated Nov 4, 2013 4:57:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;


/**
 * Group generated by hbm2java
 */
public class GroupInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7662256115305406169L;
	
	private Integer groupId;
	private String groupName;
	private String groupDescription;
	private int groupStatus;
	private Date groupCreateDate;
	
	private Set<GroupUserInfo> groupUsers;
	private transient Set<EventGroupInfo> eventGroupInfoSet;

	public Set<EventGroupInfo> getEventGroupInfoSet() {
		return eventGroupInfoSet;
	}

	public void setEventGroupInfoSet(Set<EventGroupInfo> eventGroupInfoSet) {
		this.eventGroupInfoSet = eventGroupInfoSet;
	}

	public Set<GroupUserInfo> getGroupUsers() {
		return groupUsers;
	}

	public void setGroupUsers(Set<GroupUserInfo> groupUsers) {
		this.groupUsers = groupUsers;
	}

	public GroupInfo() {
	}

	public GroupInfo(String groupName, int groupStatus, Date groupCreateDate) {
		this.groupName = groupName;
		this.groupStatus = groupStatus;
		this.groupCreateDate = groupCreateDate;
	}

	public GroupInfo(String groupName, String groupDescription, int groupStatus,
			Date groupCreateDate) {
		this.groupName = groupName;
		this.groupDescription = groupDescription;
		this.groupStatus = groupStatus;
		this.groupCreateDate = groupCreateDate;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	public int getGroupStatus() {
		return this.groupStatus;
	}

	public void setGroupStatus(int groupStatus) {
		this.groupStatus = groupStatus;
	}

	public Date getGroupCreateDate() {
		return this.groupCreateDate;
	}

	public void setGroupCreateDate(Date groupCreateDate) {
		this.groupCreateDate = groupCreateDate;
	}

}
