package teabooker.model;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class OrderInfo implements java.io.Serializable, Comparable<OrderInfo> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7650492663946848260L;
	private Integer orderId;
	private int userId;
	private int foodId;
	private int foodCount;
	private int eventId;
	private int orderStatus;
	private Date createDate;
	private String comment;
	
	private FoodInfo orderFood;


	public FoodInfo getOrderFood() {
		return orderFood;
	}

	public void setOrderFood(FoodInfo orderFood) {
		this.orderFood = orderFood;
	}

	public OrderInfo() {
	}

	public OrderInfo(int userId, int foodId, int foodCount, int eventId,
			int orderStatus, Date createDate) {
		this.userId = userId;
		this.foodId = foodId;
		this.foodCount = foodCount;
		this.eventId = eventId;
		this.orderStatus = orderStatus;
		this.createDate = createDate;
	}

	public OrderInfo(int userId, int foodId, int foodCount, int eventId,
			int orderStatus, Date createDate, String comment) {
		this.userId = userId;
		this.foodId = foodId;
		this.foodCount = foodCount;
		this.eventId = eventId;
		this.orderStatus = orderStatus;
		this.createDate = createDate;
		this.comment = comment;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getFoodId() {
		return this.foodId;
	}

	public void setFoodId(int foodId) {
		this.foodId = foodId;
	}

	public int getFoodCount() {
		return this.foodCount;
	}

	public void setFoodCount(int foodCount) {
		this.foodCount = foodCount;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Override
	public int compareTo(OrderInfo o) {
		int foodId1 = this.foodId;
		int foodId2 = o.foodId;
		return Integer.compare(foodId1, foodId2);
	}

}
