package teabooker.model;

import java.util.Set;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * ShopAddress generated by hbm2java
 */
public class ShopAddressInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5064234042427215310L;
	private Integer id;
	private int shopId;
	private String address;
	private Integer addressStatus;
	
	private transient Set<EventShopInfo> eventShopaddressInfoSet;


	public Set<EventShopInfo> getEventShopaddressInfoSet() {
		return eventShopaddressInfoSet;
	}

	public void setEventShopaddressInfoSet(
			Set<EventShopInfo> eventShopaddressInfoSet) {
		this.eventShopaddressInfoSet = eventShopaddressInfoSet;
	}

	public ShopAddressInfo() {
	}

	public ShopAddressInfo(int shopId, String address) {
		this.shopId = shopId;
		this.address = address;
	}

	public ShopAddressInfo(int shopId, String address, Integer addressStatus) {
		this.shopId = shopId;
		this.address = address;
		this.addressStatus = addressStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getAddressStatus() {
		return this.addressStatus;
	}

	public void setAddressStatus(Integer addressStatus) {
		this.addressStatus = addressStatus;
	}

}
