package teabooker.model;

import java.util.Set;

// Generated Nov 8, 2013 4:19:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Shop generated by hbm2java
 */
public class ShopInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1305310215971489970L;
	private Integer shopId;
	private String shopName;
	private String shopPhone;

	private transient Set<EventShopInfo> eventShopInfoSet;

	public Set<EventShopInfo> getEventShopInfoSet() {
		return eventShopInfoSet;
	}

	public void setEventShopInfoSet(Set<EventShopInfo> eventShopInfoSet) {
		this.eventShopInfoSet = eventShopInfoSet;
	}

	public ShopInfo() {
	}

	public ShopInfo(String shopName, String shopPhone) {
		this.shopName = shopName;
		this.shopPhone = shopPhone;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopPhone() {
		return this.shopPhone;
	}

	public void setShopPhone(String shopPhone) {
		this.shopPhone = shopPhone;
	}

}
