package teabooker.model;

import java.util.Set;

// Generated Nov 4, 2013 4:57:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * Userinfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7132108211774165620L;
	private Integer userId;
	private String userName;
	private transient String userPass;
	private String userPhone;
	private String userNickName;
	private int type;
	private String profileImg;

	private transient Set<EventUserInfo> eventUserInfoSet;
	

	public Set<EventUserInfo> getEventUserInfoSet() {
		return eventUserInfoSet;
	}

	public void setEventUserInfoSet(Set<EventUserInfo> eventUserInfoSet) {
		this.eventUserInfoSet = eventUserInfoSet;
	}

	public UserInfo() {
	}

	public UserInfo(String userName, String userPass, String userPhone,
			String userNickName, int type) {
		this.userName = userName;
		this.userPass = userPass;
		this.userPhone = userPhone;
		this.userNickName = userNickName;
		this.type = type;
	}

	public UserInfo(String userName, String userPass, String userPhone,
			String userNickName, int type, String profileImg) {
		this.userName = userName;
		this.userPass = userPass;
		this.userPhone = userPhone;
		this.userNickName = userNickName;
		this.type = type;
		this.profileImg = profileImg;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserNickName() {
		return this.userNickName;
	}

	public void setUserNickName(String userNickName) {
		this.userNickName = userNickName;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getProfileImg() {
		return this.profileImg;
	}

	public void setProfileImg(String profileImg) {
		this.profileImg = profileImg;
	}

}
